version: "3.8"

services:
  nextjs:
    build: ./
    image: noah_ui:latest
    container_name: noah
    environment:
      - NODE_ENV=${NODE_ENV}

  nginx:
    build: ./nginx
    ports:
      - 80:80
